import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getPostById, updatePost, deletePost } from '../api/posts';
import { getPhoto, uploadPhoto} from '../api/photos';
import { CloseIcon, AttachPhotoIcon } from '../assets/icons';
import { isAxiosError } from 'axios';
import type { Post } from '../models/post';
import { likePost, unlikePost } from '../api/postLikes';
import type { Photo } from '../models/photo';
import { getUserByUsername } from '../api/users';
import CommentSection from '../components/CommentSection';
import { HeartIcon } from '../assets/icons';
import './PostDetail.css';

function formatPostDate(createdAt: string, updatedAt: string | null | undefined): string {
  if (!createdAt) return '';

  const created = new Date(createdAt);
  const isEdited = updatedAt && new Date(updatedAt).getTime() > created.getTime();
  const targetDate = isEdited ? new Date(updatedAt!) : created;

  const day = String(targetDate.getDate()).padStart(2, '0');
  const month = String(targetDate.getMonth() + 1).padStart(2, '0');
  const year = targetDate.getFullYear();
  const hours = String(targetDate.getHours()).padStart(2, '0');
  const minutes = String(targetDate.getMinutes()).padStart(2, '0');

  const formattedStr = `${day}/${month}/${year} ${hours}:${minutes}`;
  return isEdited ? `Edited ${formattedStr}` : formattedStr;
}

export default function PostDetail() {
  const { postId } = useParams<{ postId: string }>();
  const navigate = useNavigate();
  const [actionLoading, setActionLoading] = useState(false);

  const user = JSON.parse(localStorage.getItem('pulse_user') || 'null');
  const currentUserId = user ? Number(user.id || user.userId) : null;

  const [post, setPost] = useState<Post | null>(null);
  const [photo, setPhoto] = useState<Photo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [authorPhotoUrl, setAuthorPhotoUrl] = useState<string | null>(null);

  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState('');

  // for media editing
  const [editMediaPreview, setEditMediaPreview] = useState<string | null>(null);
  const [editMediaCaption, setEditMediaCaption] = useState('');
  const [newFileSelected, setNewFileSelected] = useState(false);
  const [isPhotoRemoved, setIsPhotoRemoved] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [actionError, setActionError] = useState('');

  useEffect(() => {
    if (!postId) return;
    
    setLoading(true);
    getPostById(Number(postId))
      .then(data => {
        setPost(data);
        if (data.photoId != null) {
          getPhoto(data.photoId).then(setPhoto).catch(() => setPhoto(null));
        }
        if (data.username) {
          const loggedInUser = JSON.parse(localStorage.getItem('pulse_user') || 'null');
          if (loggedInUser && loggedInUser.username === data.username) {
            setAuthorPhotoUrl(loggedInUser.photoUrl || null);
          } else {
            getUserByUsername(data.username)
              .then(u => setAuthorPhotoUrl(u.photoUrl || null))
              .catch(() => setAuthorPhotoUrl(null));
          }
        }
      })
      .catch(err => {
        if (isAxiosError(err)) {
          setError(err.response?.status === 404 ? 'Post not found.' : 'Failed to load post.');
        } else {
          setError('An unexpected error occurred.');
        }
      })
      .finally(() => setLoading(false));
  }, [postId]);


  async function handleSaveEdit() {
    if (!editContent.trim()) {
      setActionError("Post content cannot be empty.");
      return;
    }

    setActionLoading(true);
    setActionError('');

    try {
      let finalPhotoId = post!.photoId;
      let finalPhotoUrl = post!.photoUrl;

      if (isPhotoRemoved) {
        // They clicked the 'X' to remove the photo
        finalPhotoId = null;
        finalPhotoUrl = null;
      } else if (newFileSelected && editMediaPreview) {
        // They selected a new file. Upload it FIRST!
        const uploadedPhoto = await uploadPhoto({
          fileUrl: editMediaPreview,
          caption: editMediaCaption.trim() || null,
        });
        // Grab the new ID generated by the backend
        finalPhotoId = uploadedPhoto.id;
        finalPhotoUrl = uploadedPhoto.fileUrl;
      }

      await updatePost(post!.id, {
        content: editContent.trim(),
        photoId: finalPhotoId,
        caption: editMediaCaption
      });
      const now = new Date().toISOString();
      setPost(prev => prev ? {
        ...prev,
        content: editContent.trim(),
        updatedAt: now,
        photoId: finalPhotoId,
        photoUrl: finalPhotoUrl
      } : null);

      if (isPhotoRemoved) {
        setPhoto(null);
      } else if (photo) {
        // If we have an existing photo, update its caption (and other fields)
        setPhoto({
          ...photo,
          caption: editMediaCaption,
          // Only update fileUrl/id if we actually changed the file
          fileUrl: newFileSelected ? (finalPhotoUrl ?? photo.fileUrl) : photo.fileUrl,
          id: finalPhotoId ?? photo.id
        });
      } else if (newFileSelected && finalPhotoId !== null && finalPhotoUrl !== null) {
          // Create a strictly typed object that matches your Photo interface
          const newPhoto: Photo = {
            id: finalPhotoId,
            albumId: null,
            // Use the OR operator (||) to provide a fallback number if currentUserId is null
            uploadedBy: currentUserId || 0,
            fileUrl: finalPhotoUrl,
            caption: editMediaCaption
          };

          setPhoto(newPhoto);
        }
      setIsEditing(false);
      // Notify the background feed to update without a hard refresh
      window.dispatchEvent(new CustomEvent('postUpdated', {
        detail: {
          id: post!.id,
          content: editContent.trim(),
          updatedAt: now,
          photoId: finalPhotoId,
          photoUrl: finalPhotoUrl
        }
      }));
    } catch (err) {
      console.error(err);
      setActionError("Failed to update post.");
    } finally {
      setActionLoading(false);
    }
  }

  async function handleDelete() {
    if (!window.confirm("Are you sure you want to delete this post?")) return;

    setActionLoading(true);
    setActionError('');

    try {
      await deletePost(post!.id);
      // Notify the background feed to remove the post
      window.dispatchEvent(new CustomEvent('postDeleted', { detail: { id: post!.id } }));
      navigate(-1); // Close modal
    } catch (err) {
      console.error(err);
      setActionError("Failed to delete post.");
      setActionLoading(false);
    }
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = () => {
      setEditMediaPreview(reader.result as string);
      setNewFileSelected(true);
      setIsPhotoRemoved(false);
    };
    reader.readAsDataURL(file);
  }

  function handleRemoveMedia() {
    setEditMediaPreview(null);
    setEditMediaCaption('');
    setIsPhotoRemoved(true);
    setNewFileSelected(false);
    if (fileInputRef.current) fileInputRef.current.value = '';
  }

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      navigate(-1);
    }
  };

  async function handleLikeToggle() {
    if (!post || actionLoading) return;

    setActionLoading(true);

    // Optimistic UI Update (Update instantly before the server responds)
    const isLiked = post.likedByCurrentUser;
    setPost(prev => prev ? {
      ...prev,
      likedByCurrentUser: !isLiked,
      likeCount: isLiked ? prev.likeCount - 1 : prev.likeCount + 1
    } : null);

    try {
      if (isLiked) {
        await unlikePost(post.id);
      } else {
        await likePost(post.id);
      }
    } catch (err) {
      // If it fails, revert the UI back to what it was
      setPost(prev => prev ? {
        ...prev,
        likedByCurrentUser: isLiked,
        likeCount: isLiked ? prev.likeCount + 1 : prev.likeCount - 1
      } : null);
    } finally {
      setActionLoading(false);
    }
  }

  if (loading) {
    return (
      <div className="post-modal-backdrop" onClick={handleBackdropClick}>
        <div className="post-modal-message">Loading post...</div>
      </div>
    );
  }

  if (error || !post) {
    return (
      <div className="post-modal-backdrop" onClick={handleBackdropClick}>
        <div className="post-modal-message post-modal-error">{error || 'Post not found'}</div>
      </div>
    );
  }

  const isPostOwner = currentUserId === post.userId;
  const avatarVar = (post.username ? (post.username.charCodeAt(0) % 3) + 1 : 1);

  return (
    <div className="post-modal-backdrop" onClick={handleBackdropClick}>
      <div className="post-modal-content">
        
        {/* LEFT COLUMN: Post Content & Info */}
        <div className="post-modal-left-pane">
          <div className="post-detail-header">
            <div className="post-detail-author">
             {authorPhotoUrl ? (
                <img 
                  className="author-avatar author-avatar--photo" 
                  src={authorPhotoUrl} 
                  alt={post.username} 
                  style={{ objectFit: 'cover', borderRadius: '50%' }} 
                />
              ) : (
                <div className={`author-avatar avatar-gradient--${avatarVar}`}>
                  {(post.username?.[0] || 'U').toUpperCase()}
                </div>
              )}
              <div className="author-info">
                <span className="author-name">@{post.username || 'username'}</span>
                <time className="author-date">
                  {formatPostDate(post.createdAt, post.updatedAt)}
                </time>
              </div>
            </div>
          </div>

          <div className="post-detail-body">
            {actionError && <p className="post-action-error">{actionError}</p>}
            
            {/* 1. Editor mode vs View mode for text */}
            {isEditing ? (
              <div className="post-edit-container">
                <textarea
                  className={`post-create__textarea ${actionError ? 'post-create__textarea--error' : ''}`}
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  disabled={actionLoading}
                  rows={3}
                  style={{ width: '100%', marginBottom: '12px' }}
                />

                {editMediaPreview && (
                  <div className="post-create__image-preview">
                    <img src={editMediaPreview} alt="Attachment preview" className="post-create__preview-img" />
                    <input
                      className="post-create__caption-input"
                      type="text"
                      placeholder="Add a caption (optional)"
                      value={editMediaCaption}
                      onChange={(e) => setEditMediaCaption(e.target.value)}
                      disabled={actionLoading}
                    />
                    <button
                      type="button"
                      className="post-create__remove-img"
                      onClick={handleRemoveMedia}
                      aria-label="Remove media"
                    >
                      <CloseIcon />
                    </button>
                  </div>
                )}

                <div className="post-create__footer" style={{ borderTop: 'none', padding: '10px 0 0 0' }}>
                  <div className="post-create__footer-left">
                    <button
                      type="button"
                      className="post-create__attach-btn"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={actionLoading || editMediaPreview !== null}
                    >
                      <AttachPhotoIcon />
                      Media
                    </button>
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept="image/*,video/*"
                      style={{ display: 'none' }}
                      onChange={handleFileChange}
                    />
                  </div>
                  <div className="actions-right">
                    <button
                      className="placeholder-action-btn edit-save"
                      onClick={handleSaveEdit}
                      disabled={actionLoading}
                    >
                      {actionLoading ? 'Saving...' : 'Save'}
                    </button>
                    <button
                      className="placeholder-action-btn edit-cancel"
                      onClick={() => { setIsEditing(false); setActionError(''); }}
                      disabled={actionLoading}
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              </div>
            ) : (
              // View mode: show text and photo only when NOT editing
              post.content && <p className="post-text">{post.content}</p>
            )}

            {!isEditing && photo && (
              <div className="post-photo-wrapper">
                <img src={photo.fileUrl} alt={photo.caption ?? 'Post attachment'} className="post-photo" />
                {photo.caption && <p className="post-caption">{photo.caption}</p>}
              </div>
            )}
          </div>

          <div className="post-detail-actions">
            <button 
              className={`post-card__like-btn ${post.likedByCurrentUser ? 'post-card__like-btn--liked' : ''}`}
              onClick={handleLikeToggle}
              disabled={actionLoading}
            >
              <HeartIcon fill={post.likedByCurrentUser ? 'currentColor' : 'none'} />
              <span>{post.likeCount > 0 ? post.likeCount : 'Like'}</span>
            </button>

            {isPostOwner && !isEditing && (
              <div className="actions-right">
                <button
                  className="placeholder-action-btn edit"
                  onClick={() => {
                    setIsEditing(true);
                    setEditContent(post.content);
                    if (photo) {
                      setEditMediaPreview(photo.fileUrl);
                      setEditMediaCaption(photo.caption || '');
                    } else {
                      setEditMediaPreview(null);
                      setEditMediaCaption('');
                    }
                    setIsPhotoRemoved(false);
                    setNewFileSelected(false);
                  }}
                  disabled={actionLoading}
                >
                  Edit
                </button>
                <button
                  className="placeholder-action-btn delete"
                  onClick={handleDelete}
                  disabled={actionLoading}
                >
                  {actionLoading ? 'Deleting...' : 'Delete'}
                </button>
              </div>
            )}
          </div>
        </div>

        {/* RIGHT COLUMN: Interactive Comment Section */}
        <div className="post-modal-right-pane">
          <div className="post-modal-right-header">
            <h3>Comments</h3>
            <button className="post-modal-close" onClick={() => navigate(-1)} aria-label="Close">
              ✕
            </button>
          </div>
          
          <div className="post-modal-comments-container">
            <CommentSection 
              postId={post.id} 
              currentUserId={currentUserId} 
              isPostOwner={isPostOwner} 
            />
          </div>
        </div>

      </div>
    </div>
  );
}