spring.application.name=monitoring-service


###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${DB_IP:localhost}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:postgres}
database.password = ${DB_PASSWORD:root}
database.name = ${DB_DBNAME:monitoring-db}

spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://monitoring-db:5432/monitoringdb
spring.datasource.username=monitoring
spring.datasource.password=monitoringpass


# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8084}
security.jwt.secret=VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC
internal.token=super-secret-sync



spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

monitoring.queues.device-data=device.data.queue

monitoring.queues.overconsumption=overconsumption.queue
overconsumption.queue=overconsumption.queue

sync.device.queue=device.sync.queue

device.data.queue=device.data.queue