# Server
server.port=${PORT:8087}

spring.application.name=customer-support-service

# RabbitMQ (default local; in docker profile we'll point to rabbitmq)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Chatbot queues
# Chatbot queues
chat.request.queue=chat.user.in
chat.response.queue=chat.user.out

# Support queues (pentru consistency)
support.queues.chatUserIn=chat.user.in
support.queues.chatUserOut=chat.user.out

# Security
security.jwt.secret=VZk9R7q2eFj8Ls3pT4xN6wQy8Ua1BmCk5GhDfJ0Hs2Lp3Rv7Yq4Zd8Xe9TtVbWnC

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Helpful during dev
logging.level.org.springframework.amqp=INFO
logging.level.com.example.customersupport=INFO

ai.gemini.apiKey=${GEMINI_API_KEY:}
ai.gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
ai.gemini.baseUrl=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}



spring.rabbitmq.listener.simple.default-requeue-rejected=false
