server:
  port: 8086

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

websocket:
  queues:
    overconsumption: overconsumption.queue
    chatUserIn: chat.user.in
    chatUserOut: chat.user.out
  endpoint: /ws
  allowed-origins: "*"
